name: Run jmeter tests

on:
  push:
    branches:
      - main
      - jmeter
  pull_request:
    branches:
      - main

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install dependencies for BE
      - name: Install backend dependencies
        run: npm install

      # Install dependencies for FE
      - name: Install client dependencies
        run: |
          cd client
          npm install

      # Install JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xzf apache-jmeter-5.5.tgz
          export PATH=$PATH:$(pwd)/apache-jmeter-5.5/bin

      - name: Start up Server
        env:
          PORT: 6060
          DEV_MODE: development
          MONGO_URL: mongodb+srv://username:d3zZ2uuoiqobR3xf@cs4218-test-cluster.vvmcw.mongodb.net/ecommerce_database
          JWT_SECRET: HGFHGEAD12124322432
          BRAINTREE_MERCHANT_ID: hmrc3kfrt2xrvtvp
          BRAINTREE_PUBLIC_KEY: d3rnqcjwn7zk4fpt
          BRAINTREE_PRIVATE_KEY: 767ed9ddd903781349d4c2af441f8eaa
        run: npm run server &

      - name: Start up Client
        run: npm run client &

      # Run JMeter tests
      - name: Run JMeter Tests
        run: npm run test:jmeter

      # Upload JMeter Results
      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: jmeter/outputs/*.csv

      # Analyze JMeter Results
    #   - name: Analyze Results with Latency Lingo
    #     uses: latency-lingo/github-action@v0.0.2
    #     with:
    #       api-key: e13d313f-efb0-41cf-af3a-ae45dce3060f
    #       file: jmeter/outputs/*.csv
    #       label: Automated JMeter Test Results
    #       format: jmeter

      - name: Analyze Results with Latency Lingo
        run: |
            # Make sure the CLI is executable
            chmod +x ./latency-lingo-cli

            # Iterate over each CSV file in the outputs folder
            for file in jmeter/outputs/*.csv; do
            echo "Processing $file with Latency Lingo"
            ./latency-lingo-cli publish --file "$file" \
                --api-key "e13d313f-efb0-41cf-af3a-ae45dce3060f" \
                --label "Automated JMeter Test Results" \
                --format "jmeter" \
                --env "production" || exit 1
            done
