name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies for BE
      - name: Install backend dependencies
        run: npm install

      # Install dependencies for FE
      - name: Install client dependencies
        run: |
          cd client
          npm install

      # Install Playwright dependencies and browsers
      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Install Playwright Browsers
        run: npx playwright install

      # Run Playwright tests
      - name: Run Playwright tests
        env:
          PORT: 6060
          DEV_MODE: development
          MONGO_URL: mongodb+srv://username:d3zZ2uuoiqobR3xf@cs4218-test-cluster.vvmcw.mongodb.net/ecommerce_database
          JWT_SECRET: HGFHGEAD12124322432
          BRAINTREE_MERCHANT_ID: hmrc3kfrt2xrvtvp
          BRAINTREE_PUBLIC_KEY: d3rnqcjwn7zk4fpt
          BRAINTREE_PRIVATE_KEY: 767ed9ddd903781349d4c2af441f8eaa
        run: npm run test:playwright
        continue-on-error: true

      # Upload Playwright test report as an artifact
      - name: Upload Playwright test report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
